### PR TITLE
Add information about format to decks

### PR DESCRIPTION
**Pull request by mmeldo**
Info if deck is WWE or Old Timer format.
image

### CODE REVIEW

**Comment by mmeldo** [comment]
@stopfstedt can you please look at this and let me know what do you think? I added som logic that will automatically update tag for the deck based on the format. Also added some colors to better distinguish them, even though I am not sure about that.

Code is not final, just a first draft.

**Comment by stopfstedt** [comment]
hey @mmeldo - i see where you're going with this, but i wonder if it would be cleaner to make this a data attribute on the cards themselves rather than juggling ranges based on TCAR pack number or the likes. 
if we could filter cards by format (or card pool) based on some attribute, that also make it easier to improve the deckbuilder. if you're free next week then perhaps we could brainstorm this a bit.

**Comment by mmeldo** [comment]
@stopfstedt sorry for not being clear enough in my update. I fully agree with you that the way I have it in this change is not how we should do it. It was just a clutch to try the UI and decide how we want it to look like. I will definitely change it.
I will look into the colors if they are ok, but yeah this will have to wait until we decide how to proceed with #11 . I have some ideas but will post there.

**Comment by mmeldo** [comment]
contrast updated to make it AA compliant. but I do not believe it will be a problem for color blind people since it also contains text informing about the format.

**Comment by stopfstedt** [comment]
based on the feedback received in https://github.com/townteki/dtdb/issues/11, i think it's OK to move forward with this implementation. so please keep at it :)

**Comment by mmeldo** [comment]
@stopfstedt I am still not sure I really like it. Maybe just adding a `format` attribute to the pack saying `wwe` for TCaR packs and later and having null for earlier packs.
Or at least to have just one function in the dtdb that would let you know if card is WWE format or not ...

**Comment by mmeldo** [comment]
@stopfstedt I spent some time trying to have one place that will decide what the format will be, but could not find any workable solution. Then I got lazy and just updated the current solution and added some comments.
Since my dev is so slow, I did not properly test is. Could you please test if the solution is fine and if that works for you?

**Comment by stopfstedt** [comment]
i'll check it out over the weekend, will keep you posted. thanks for taking a stab at it in any case!!

**Comment by stopfstedt** [comment]
@mmeldo  I need to kick the review on this into next week, apologies. 

I'll have a look this Tuesday for sure.

**Comment by mmeldo** [comment]
@stopfstedt no problem. in the meantime, one question: When you do some change and want to test locally, what does it require to propagate the changes? I am usually restarting the apache and clearing browser cache, but it looks like it does not work anymore as my last update I did for this PR does not show up.

**Comment by stopfstedt** [comment]
> @stopfstedt no problem. in the meantime, one question: When you do some change and want to test locally, what does it require to propagate the changes? I am usually restarting the apache and clearing browser cache, but it looks like it does not work anymore as my last update I did for this PR does not show up.

for PHP and TWIG template changes, cache clearing via `bin/console cache:clear` should be all that's necessary.
for frontend assets (JS/CSS) changes, I usually bump the version number after making changes, in this file: https://github.com/townteki/dtdb/blob/master/config/packages/framework.yaml#L4
that will bust the browser cache on page-refresh since that version number is appended to all asset URLs. oh, and I don't think that restarting Apache is necessary.

**Review by stopfstedt — APPROVED** [review]
LGTM. made a few changes in the PHP code, otherwise this was fine as submitted. thanks!!

**Comment by mmeldo** [comment]
@stopfstedt thanks a lot for the updates and info

**Pull request merged**
